name: CI

on:
  push:
    branches: [ "rework" ]
  pull_request:
    branches: [ "rework" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v5
    - name: Build Binaries
      run: cargo build --profile release
    - name: Collect Binaries
      shell: bash
      run: |
        mkdir dist
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          cp target/release/marshalconv.exe dist/marshalconv_windows.exe
          cp target/release/rpgtool.exe dist/rpgtool_windows.exe
        else
           cp target/release/marshalconv dist/marshalconv_linux
           cp target/release/rpgtool dist/rpgtool_linux
        fi
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: rpgtool-${{ matrix.os }}
        path: dist/
        
