name: compile-release

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v5
    # https://github.com/rust-lang/cargo/issues/7895#issuecomment-2323050826
    - name: Build
      run: 
        mkdir dist
        OUTPUT="$(cargo build --message-format=json-render-diagnostics --release)"
        ARTIFACTS="$(echo $OUTPUT | jq -sr '[.[] | select(.reason == "compiler-artifact") | select(.executable != null)] | map ( .executable ) []')"
        for ARTIFACT in $ARTIFACTS; do cp $ARTIFACT dist/; done
    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        files: dist/*
        
